sanic_ext/extensions/openapi/openapi.py

There is a problem that the sub-content disappears when using the body decorator due to the validation handler.
I solved it by simply getting information on existing functions.

Fix bugrisk on openapi body decorator

---

sanic_ext/__init__.py
sanic_ext/config.py
sanic_ext/extensions/openapi/blueprint.py
sanic_ext/extensions/openapi/ui/swagger.html

Closes #6 
It seems that the CDN we were using no longer hosts the Swagger UI assets. Furthermore, the Cloudflare CDN is version only (no `latest`). Therefore, this PR does two things:
1. Changes the CDN to CF
2. Introduces a config value to change the swagger version

Change CDN for Swagger UI

---

sanic_ext/__init__.py
sanic_ext/extensions/http/cors.py

When adding the allowed methods header, routes were being looked up using `route.parts`. This is the actual raw values rather than `route.segments` which allows for dynamic placeholders. Therefore, when trying to add headers to a dynamic route, the methods were not retrievable.

Fix bug with alowed methods on a dynamic route

---

sanic_ext/extensions/openapi/types.py

Fixes #12 
This allows `Optional` to be properly parsed.
```python
class Foo(TypedDict):
bar: Optional[bool]
class FooBar(TypedDict):
foo: Optional[Foo]
bar: Optional[str]
...
@openapi.response(200, {"application/json": FooBar})
```

Allow Optional to be used on an annotation and properly translate to OAS

---

setup.py

Unpin the linters' version to let them work with `make pretty` in the repo.
In my testing, with the current pinned version of the linters, errors below may occur:
Command: `isort --line-length 79 --trailing-comma -m 3 sanic_ext tests`
```
isort --line-length 79 --trailing-comma -m 3 sanic_ext tests
usage: isort [-h] [-a ADD_IMPORTS] [-ac] [-af] [-b KNOWN_STANDARD_LIBRARY] [-c] [-ca] [-cs] [-d] [-df] [-ds] [-dt] [-e] [-f KNOWN_FUTURE_LIBRARY] [-fas] [-fass] [-ff FROM_FIRST] [-fgw [FORCE_GRID_WRAP]] [-fss] [-i INDENT]
[-j JOBS] [-k] [-l LINE_LENGTH] [-lai LINES_AFTER_IMPORTS] [-lbt LINES_BETWEEN_TYPES] [-le LINE_ENDING] [-ls] [-m {0,1,2,3,4,5,6,7}] [-nis] [-nlb NO_LINES_BEFORE] [-ns NOT_SKIP] [-o KNOWN_THIRD_PARTY] [-ot]
[-p KNOWN_FIRST_PARTY] [-q] [-r] [-rm REMOVE_IMPORTS] [-rr] [-rc] [-s …
```

Unpin Linters Version

---

sanic_ext/bootstrap.py
sanic_ext/extensions/injection/constructor.py
sanic_ext/extensions/injection/injector.py
sanic_ext/extensions/injection/registry.py
sanic_ext/utils/string.py
tests/extensions/injection/test_add_dependency.py
tests/extensions/injection/test_dependency.py
tests/extensions/injection/test_injection.py
tests/extensions/injection/test_injection_registry.py
tox.ini

This PR allows for the constructors of dependencies to declare nested dependencies.
```python
class A:
...
class B:
def __init__(self, a: A):
self.a = a
class C:
def __init__(self, b: B):
self.b = b
def get_a(request: Request):
return A()
def get_b(request: Request, a: A):
return B(a)
def get_c(request: Request, b: B):
return C(b)
ext.add_dependency(A, get_a)
ext.add_dependency(B, get_b)
ext.add_dependency(C, get_c)
```
This also adds a convenience method that:
1. Adds an item to the application `ctx`
2. creates the constructor
3. adds the injection
```python
class Foo:
def bar(self):
return "foobar"
@app.before_server_start
async def setup_foo(app, _):
ext.dependency(Foo())
@app.get("/getfoo")
async def getfoo(request: Request, foo: Foo):
return text(foo.bar())
```
To follow the Sanic …

Add cascading dependency injection

---

sanic_ext/extensions/openapi/openapi.py
tests/extensions/openapi/test_parameter.py
tests/extensions/openapi/utils.py

Related issue: https://github.com/sanic-org/sanic-ext/issues/18

Pass `parameter.fields` When `parameter` is being Passed in

---

sanic_ext/extensions/openapi/openapi.py
tests/extensions/openapi/test_parameter.py

Related issue: https://github.com/sanic-org/sanic-ext/issues/11
`location` and `in` often mess up in the current version. I think this is only a temporary solution and we need to rethink this and make a rule like "using location everywhere except exporting it to the real docs" to declared when to use `location` and when to use `in`. Since `in` is a Python key word, making use of `location` everywhere except the real docs seems a good idea.

Temp Fix for openapi.definition with Parameter object

---

sanic_ext/__init__.py
sanic_ext/bootstrap.py
sanic_ext/extensions/injection/extension.py
sanic_ext/extensions/injection/registry.py
sanic_ext/extensions/openapi/extension.py
setup.py
tests/extensions/injection/test_add_dependency.py
tests/extensions/injection/test_dependency.py

The main purpose of this is to make the integration into `Sanic` a little smoother. See https://github.com/sanic-org/sanic/pull/2308
For example, the output to logs at startup are moved to a separate location so that the app can be extended either before or at startup time, and still have them generated in a consistent location.

Add flexibility in Extend declaration

---

sanic_ext/bootstrap.py
sanic_ext/extensions/openapi/builders.py
sanic_ext/extensions/openapi/constants.py
sanic_ext/extensions/openapi/definitions.py
sanic_ext/extensions/openapi/extension.py
sanic_ext/extensions/openapi/openapi.py
sanic_ext/extensions/openapi/types.py
tests/extensions/openapi/test_security.py
tests/extensions/openapi/utils.py
tox.ini

This adds an API to work with OAS `SecuritySchemes` and add `security` to the application or operations.
- Adds access to the spec object on the extension bootstrapper:
```python
app.ext.openapi.describe(
"Testing API", version="1.2.3", description="This is desc"
)
```
- Adds a `secure` method to enable application wide `security`:
```python
app.ext.openapi.secured()
app.ext.openapi.secured("my_token")
app.ext.openapi.secured(my_oauth2=["one:two"])
app.ext.openapi.secured({"my_oauth2": ["one:two"]})
```
- Or, you can put them on the operation level:
```python
@app.get("/")
@openapi.secured("my_token")
async def handler(request: Request):
return json({"foo": "bar"})
```
- Adds a `add_security_scheme` to create `SecurityScheme` objects:
```python …
```

Add authorization to openapi

---

sanic_ext/__init__.py
sanic_ext/bootstrap.py
sanic_ext/extensions/base.py
sanic_ext/extensions/http/methods.py
tests/extensions/test_startup.py

This PR removes the singleton pattern from extensions and localizes each startup to a single extension. By separating them, we should more easily allow for testing and multiple applications.

Add support for multiple starts of extensions

---

Makefile
pyproject.toml
sanic_ext/__init__.py
setup.cfg
setup.py
tests/extensions/openapi/test_body.py
tests/extensions/openapi/test_parameter.py
tests/extensions/openapi/test_tag.py
tox.ini

Pros:
1. The complex logic in `setup.py` was removed and `setup.py` is kept at minimal. "Avoid executing arbitrary scripts and boilerplate code" (https://setuptools.pypa.io/en/latest/userguide/quickstart.html#transitioning-from-setup-py-to-setup-cfg).
Cons:
1. Few packages implemented this, so there might be unknown bugs or issues.
2. The Python community is switching to putting meta in `pyproject.toml` rather than `setup.cfg` or `setup.py` in the near future. So, we will probably need to switch again in the future. [PEP621](https://www.python.org/dev/peps/pep-0621/)
Any thought?

Move metadata to `setup.cfg`

---

sanic_ext/extensions/openapi/types.py

Closes #42 
```
class Test:
foobar: Optional[List[str]]
@openapi.body({"application/json": Test})
```

Properly make schema for nullable lists

---

sanic_ext/extensions/openapi/definitions.py
sanic_ext/extensions/openapi/types.py
tests/extensions/openapi/test_decorators.py

Support the usage of `dict` annotations:
```python
class Something:
a: Dict[str, int]
b: dict[str, bool]
```

Support dict annotations

---

sanic_ext/config.py
sanic_ext/extensions/openapi/blueprint.py
sanic_ext/extensions/openapi/builders.py
sanic_ext/extensions/openapi/ui/swagger.html

1. Protocol type (https) added to CDN URLs, to ensure security transportation and to resolve the warnings by IDE (VS Code).
2. Pump up Swagger UI Version from 4.1.0 to 4.10.3. 
4.10.3 is currently the most popular version of Swagger UI and it resolved a security issue compared with 4.1.0
(The security issue was resolved in all versions >= 4.1.3, details: https://security.snyk.io/vuln/SNYK-JS-SWAGGERUI-2314885)
Unit testing passed but it probably needs more manual (eye) testing due to the natures of UI stuff, will be done in days.
3. Added some type annotations to make the dev experience with IDEs better.

Update Swagger UI Version; Adding Type Annotations

---

sanic_ext/__init__.py
sanic_ext/bootstrap.py
sanic_ext/extensions/base.py
sanic_ext/extensions/http/extension.py
tests/conftest.py
tests/extensions/openapi/test_body.py
tests/extensions/openapi/test_decorators.py
tests/extensions/openapi/test_deprecated.py
tests/extensions/openapi/test_exclude.py
tests/extensions/openapi/test_external_docs.py
tests/extensions/openapi/test_parameter.py
tests/extensions/openapi/test_summary.py
tests/extensions/openapi/test_tag.py
tests/extensions/test_startup.py

It can be somewhat difficult to add an extension if `app.extend` is not being explicitly called. This PR enables the API [as seen here](https://github.com/ahopkins/mayim) which makes it much easier for extensions to be added:
```python
app = Sanic(__name__)
Extend.register(
MayimExtension(
executors=[CityExecutor], dsn="postgres://..."
)
)
```

Add API for preregistering Extensions

---

sanic_ext/extras/validation/decorator.py
tests/extra/test_validation_dataclass.py

This small PR fix the issue described in https://github.com/sanic-org/sanic-ext/issues/92
TLDR: We didn't handle the class-based view case with the @validate decorator, so I changed the decorator to not use the first arg as the request by default.

Fix issue #92 - @validate decorator not working for class-based views

---

sanic_ext/bootstrap.py
sanic_ext/config.py
sanic_ext/extensions/health/endpoint.py
sanic_ext/extensions/health/extension.py
sanic_ext/extensions/health/monitor.py

Requires https://github.com/sanic-org/sanic/pull/2499
TODO:
- shows all PIDs
- number of current open HTTP connections
- number of requests served
- uptime

Add health monitor

---

sanic_ext/extensions/openapi/definitions.py
tests/extensions/openapi/test_decorators.py

Closes #125 
```python
from sanic import Sanic, json
from sanic_ext import validate, openapi
from pydantic import BaseModel, Field
class Test(BaseModel):
foo: str = Field(description="Foo Description", example="FOOO")
bar: str = "test"
app = Sanic("test")
@app.get("/")
@openapi.definition(
body={'application/json': Test.schema()},
)
@validate(json=Test)
async def get(request):
return json({})
```

Allow dict schema definitions in body requests

---

sanic_ext/__init__.py
sanic_ext/extras/request.py
setup.cfg
tests/conftest.py
tests/extra/test_request_counted.py

Coming off the discussion [re: the worker manager](https://www.youtube.com/watch?v=m8HCO8NK7HE&t=1976s), I implemented the idea of adding a request counter. I thought of a few different strategies. Most important to me was that it not be forced upon users who do not opt in.
The obvious first choice was of course `config`. But, I do not want to even include a check for this on *every* request. I thought about using a touchup scheme, but we do not have one that is currently setup for general conditional checks. Maybe we should, but that is outside the scope here.
Doing it on `Request.__init__` is the easiest. So, I thought perhaps as a subclass we can get the result without any of the consequences. It does however bring the question about whether a self-contained opinionated piece of logic …

Add request counter

---

sanic_ext/extensions/openapi/openapi.py
sanic_ext/extras/serializer/decorator.py
sanic_ext/extras/validation/decorator.py

Currently mypy disables type checking on functions using any of these decorators because they are "untyped" (which they are).
This PR adds typehints to affected decorators (might've missed some).
```py
from sanic import Sanic, text, Request, HTTPResponse
from sanic_ext import openapi
app = Sanic("testapp")
@app.get("/")
@openapi.summary("Greets the world")
async def root(request: Request) -> HTTPResponse:
return text("Hello world!")
```
```
$ mypy --strict test.py
test.py:8: error: Untyped decorator makes function "root" untyped
Found 1 error in 1 file (checked 1 source file)
```
With PR:
```
$ mypy --strict test.py
Success: no issues found in 1 source file
```

Add typehints to some decorators

---

sanic_ext/bootstrap.py
sanic_ext/extensions/templating/extension.py
tests/extensions/templating/test_templating.py

Added the `app.url_for` function for use in Jinja2 templates as requested in #87. 
Useful for referencing static files and endpoints in html templates. e.g.
- `{{ url_for('static', filename='styles.css') }}`
- `{{ url_for('dashboard') }}`
`url_for` is available within Jinja2 templates for Flask by default as part of the standard context (https://flask.palletsprojects.com/en/2.2.x/templating/). There may be other useful variables / functions to also add by default. e.g. `session` for logged in user details.

added url_for function for use in Jinja2 templates

---

sanic_ext/extras/validation/clean.py
sanic_ext/extras/validation/decorator.py
sanic_ext/extras/validation/setup.py
sanic_ext/extras/validation/validators.py
tests/extra/test_validation_attrs.py
tests/extra/test_validation_dataclass.py
tests/extra/test_validation_pydantic.py
tox.ini

Fixes #153
Fixes #147 
This will inspect the intended param type for query and form validation for pydantic and attrs and attempt to coerce from list to single item if that is what is expected, and leave it alone otherwise.

Coerce param types for pydantic/attrs in validation

---

sanic_ext/utils/route.py

We have a better method for identifying static route definitions. Let's use that instead of the name which is modifiable.
Closes #155

Hide static handlers by flag not name

---

sanic_ext/extensions/http/methods.py
tests/extensions/http/test_methods.py

Closes #148 
Requires https://github.com/sanic-org/sanic/pull/2639

Pass unquote thru add_route

---

sanic_ext/extensions/openapi/definitions.py
sanic_ext/extensions/openapi/types.py
sanic_ext/utils/typing.py
tests/extensions/injection/test_injection_registry.py
tests/extensions/openapi/test_decorators.py
tests/extensions/openapi/test_typing.py
tox.ini

Closes #136
Fixes a side effect of #130 to allow for both:
```python
@openapi.definition(
body={"application/json": Test.schema()},
)
```
```python
@openapi.definition(
body={"application/json": {"test": str}}
)
```

Allow dict of annotations

---

sanic_ext/extensions/openapi/definitions.py
sanic_ext/extensions/openapi/openapi.py
sanic_ext/extensions/openapi/types.py
tests/extensions/openapi/test_model_to_spec.py

Closes #152
```python
class Alert(BaseModel):
hit: dict[str, Any]
last_updated: datetime
@pydataclass
class AlertResponse:
alert: Alert
rule_id: str
```
This will automatically drop all references and pydantic classes into components:
```json
{
"openapi": "3.0.3",
"info": {
"title": "API",
"version": "1.0.0",
"contact": {}
},
"paths": {
"/": {
"get": {
"operationId": "get~handler",
"summary": "Handler",
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/AlertResponse"
}
}
}
},
"responses": {
"default": {
"description": "OK"
}
}
}
}
},
"tags": [],
"servers": [],
"security": [],
"components": {
"schemas": {
"Alert": {
"title": "Alert",
"type": "object",
"properties": {
"hit": {
"title": "Hit",
"type": "object"
},
"last_updated": {
"title": "Last …
```

Elegantly handle Pydantic model schema

---

sanic_ext/extensions/openapi/blueprint.py

Closes #166 
When using `SERVER_NAME`, will use the docs external root as HTML prefix.
```python
app.config.SERVER_NAME = "localhost:8888/proxy"
```

Use external address when SERVER_NAME is defined

---

sanic_ext/config.py
sanic_ext/extensions/logging/logger.py
tests/extensions/logging/test_custom_background_logger.py

Hi, the background logger is an excellent extension helping me log all my messages from a background process, with multiple processes.
But, it's not support to log any other logger backgrounding except `"sanic.access", "sanic.error", "sanic.root"`.
This PR is an attempt to support logging other custom loggers in the background.
to use:
```python
from sanic import Sanic
app = Sanic("MyApp")
app.config.LOGGING = True
app.config.LOGGERS = [
"my_logger"
]
```
The default value of `app.config.LOGGERS = ["sanic.access", "sanic.error", "sanic.root"]`,
which is the same with `(root_logger, access_logger, error_logger)`

Supporting custom logger in the background

---

sanic_ext/extensions/injection/constructor.py
sanic_ext/extensions/openapi/types.py
sanic_ext/extras/validation/check.py
sanic_ext/extras/validation/schema.py
sanic_ext/utils/typing.py
tests/extensions/openapi/test_model_fields.py
tests/extra/test_validation_msgspec.py
tox.ini

I've recently been looking at [msgspec](https://jcristharif.com/msgspec/index.html) to see if it can function as a `dataclass` replacement for a future Sanic project with dependency injection, as listed [in the docs](https://sanic.dev/en/plugins/sanic-ext/injection.html#basic-implementation)
I don't know if this integration is a good idea or not, but since I did the work to explore the idea, I thought I'd show it for commentary.
This change did require a number of specialized checks, and I attempted to match the existing style as closely as possible.  `test_validation_msgspec.py` is just a copy of `test_validation_attrs.py`, but with `msgspec.Struct` instead of `@define`.  Please let me know if there is a better testing strategy there.
Also, there is currently an open issue at [msgspec …

Add support for msgspec injection

---

sanic_ext/extensions/health/monitor.py

Similar to #202 / #206- this reduces CPU util pretty drastically on my host- like 150% at "idle" down to 0-2%. Setup is M1 Mac running Sanic in Docker.

Reduce healthcheck CPU

---

sanic_ext/extensions/openapi/blueprint.py
tests/extensions/openapi/test_func_handler.py

This comes from a discussion on the forums where classmethods and instance methods (not from a CBV) would not render as defined routes. This resulted because the bound methods were used as routes, and the definitions stores as functions. This PR will check if the handler does not exist, if there is a `__func__`, and if that `__func__` is defined. In that case, then it will use that as the defined handler and not recreate a default route definition.

When appropriate use a __func__ handler

---

sanic_ext/config.py
sanic_ext/extensions/http/methods.py
sanic_ext/extensions/injection/injector.py
tests/extensions/injection/test_injection_config.py

Fixes the issue where an early request before `after_server_start` is complete a dependency injection will fail.
Requires: https://github.com/sanic-org/sanic-routing/pull/76
Requires: https://github.com/sanic-org/sanic/pull/2822

Fix late dependency registration

---

sanic_ext/extensions/http/cors.py

In case the CORS_ORIGINS value is a comma separated string but with spaces in between them like
`https://google.com, http://localhost:3000`. In this case only the first URL is whitelisted. Stripping the spaces fixes the issue.
My team spent half of the day debugging this :)

chore: strip CORS_ORIGINS before assigning value

---

sanic_ext/extensions/openapi/definitions.py
sanic_ext/extras/validation/setup.py
sanic_ext/extras/validation/validators.py
tests/extensions/openapi/test_model_spec.py
tests/extra/test_validation.py

Add support for using [msgspec](https://jcristharif.com/msgspec/index.html) in `openapi.Component` and with validation -- `@validate()`
I also parameterized the tests in `test_validation` to verify that `msgspec` worked, but I also added the equivalent `attrs` and `pydantic` tests as well to make sure that all cases were covered.
If I wasn't sure about compatibility, I used inline imports -- as opposed to top-of-file imports -- for `msgspec`.

Add msgspec support for openapi.Component and @validate()

---

sanic_ext/extensions/logging/logger.py

Fixes #254 : "Removing handlers in Background Logger extension removes only one handler."
Issue only occurs when there are more than one handler to remove from the list of handlers. Please refer to comments here #254

FIx handler list mutation while removing handlers
