sanic_ext/__init__.py, sanic_ext/extensions/http/methods.py, sanic_ext/extensions/injection/injector.py, sanic_ext/extensions/injection/registry.py, tests/extensions/injection/test_injection.py
=> Setup injections on CBV

sanic_ext/extensions/openapi/blueprint.py, sanic_ext/extensions/openapi/ui/redoc.html, sanic_ext/extensions/openapi/ui/swagger.html, sanic_ext/utils/route.py
Fix hard coding of /docs in html, allow empty OAS_URL_PREFIX
Fixes: https://github.com/sanic-org/sanic-ext/issues/16
=> Fix hard coding of /docs in html, allow empty OAS_URL_PREFIX

.github/workflows/python-package.yml, sanic_ext/__init__.py, sanic_ext/bootstrap.py, sanic_ext/extensions/http/extension.py, sanic_ext/extensions/injection/constructor.py, setup.py, tests/extensions/injection/test_add_dependency.py, tox.ini
Some post-release fixed:
- version check to ignore `dev` in Sanic version check
- stop early on no CORS config check
- ignore return type annotations when evaluating injection patterns
=> Minor tweaks

tests/extensions/openapi/test_exclude.py
Add a test case for exclude decorator.
=> Test Exclude

sanic_ext/extras/validation/check.py, sanic_ext/extras/validation/schema.py, sanic_ext/extras/validation/setup.py, tests/extra/__models__.py, tests/extra/test_validation_dataclass.py
=> Allow for default_factory to succeed

sanic_ext/extensions/openapi/openapi.py
=> Fix `parameter` and `exclude` typings

sanic_ext/extensions/http/methods.py, sanic_ext/extensions/injection/injector.py, tests/extensions/injection/test_add_dependency.py
=> Support websocket injection

sanic_ext/extras/validation/schema.py, sanic_ext/utils/typing.py, tests/extra/__models__.py, tests/extra/test_validation_dataclass.py
=> Add support for 3.10 UnionType validation

sanic_ext/extensions/openapi/blueprint.py, sanic_ext/extensions/openapi/builders.py
=> Add support for multiple applications

setup.cfg
- https://github.com/sanic-org/sanic/pull/2418
- https://github.com/sanic-org/sanic-ext/pull/68
- https://github.com/sanic-org/sanic-routing/pull/61
- https://github.com/sanic-org/sanic-testing/pull/36
=> Bump version and 22.3

sanic_ext/extensions/openapi/types.py, setup.cfg
=> Support type hint checking on handlers earlier than 3.10

sanic_ext/extensions/templating/render.py, tests/extensions/templating/test_templating.py
=> Added render from source option

sanic_ext/extensions/injection/constructor.py, sanic_ext/extensions/openapi/types.py, tests/extensions/injection/test_add_dependency.py
=> Account for circular injection visiting the same nodes

sanic_ext/extensions/injection/constructor.py, tests/extensions/injection/test_injection_registry.py
=> fix(dependancy): check issubclass of exempt hints

sanic_ext/extras/serializer/decorator.py, tests/extra/test_serializer.py
serializer not transfer parameters；
serializer 装饰器无法传输请求中的参数；
=> fix: serializer not transfer parameters

sanic_ext/extensions/openapi/types.py, tests/extensions/openapi/test_schema.py
=> Better serialization of objects

sanic_ext/extensions/openapi/blueprint.py, tests/extensions/openapi/test_config.py
=> Add API_SCHEMES parsing

sanic_ext/extensions/openapi/types.py, setup.cfg, tests/extensions/openapi/test_schema.py
=> Proper check of Pydantic properties on OAS

sanic_ext/extensions/openapi/types.py, sanic_ext/extras/validation/decorator.py
=> nonemptystr to string type

sanic_ext/extras/validation/check.py, sanic_ext/extras/validation/decorator.py, sanic_ext/extras/validation/schema.py, sanic_ext/utils/typing.py, tests/extra/__models__.py, tests/extra/test_validation_dataclass.py
=> Better validation handling for optional types

sanic_ext/extensions/openapi/blueprint.py, sanic_ext/extensions/openapi/builders.py, sanic_ext/extensions/openapi/definitions.py, sanic_ext/extensions/openapi/types.py
=> Prefer autodoc over defines

sanic_ext/extensions/injection/constructor.py, tests/extensions/injection/test_add_dependency.py, tests/extensions/openapi/test_parameter.py
=> fix: injecting async dependencies

sanic_ext/extensions/http/methods.py, sanic_ext/extensions/injection/constructor.py, sanic_ext/extensions/injection/registry.py, sanic_ext/extras/validation/check.py, sanic_ext/extras/validation/schema.py, sanic_ext/extras/validation/setup.py, sanic_ext/utils/typing.py, setup.cfg, tests/extensions/http/test_methods.py, tests/extensions/injection/test_add_dependency.py
Adds support for class constructors to by used for injection:
```python
class Alpha:
...
class Beta:
def __init__(self, alpha: Alpha) -> None:
self.alpha = alpha
app.ext.add_dependency(Alpha)
app.ext.add_dependency(Beta)
```
=> Add support for class constructor injections

sanic_ext/extensions/openapi/types.py
=> Remove classes from schema properties

sanic_ext/extensions/openapi/openapi.py, sanic_ext/extensions/templating/engine.py, sanic_ext/extensions/templating/render.py, sanic_ext/extras/validation/decorator.py, sanic_ext/utils/extraction.py, tests/extensions/openapi/test_decorators.py
=> Add request extraction on decorators

sanic_ext/bootstrap.py, sanic_ext/config.py, sanic_ext/extensions/base.py, sanic_ext/extensions/health/extension.py, sanic_ext/extensions/logging/extension.py, sanic_ext/extensions/logging/logger.py, sanic_ext/extensions/openapi/extension.py
Adds an extension to offload all logging to a separate process.
=> Add logging process extension

sanic_ext/extensions/http/methods.py, sanic_ext/extensions/injection/injector.py, tests/extensions/injection/test_dependency.py
=> Injections for HEAD requests

sanic_ext/config.py, sanic_ext/extensions/openapi/blueprint.py
=> feat: serve oauth2-redirect.html with swagger

sanic_ext/config.py, sanic_ext/extensions/openapi/blueprint.py, tests/extensions/openapi/static/petstore.json, tests/extensions/openapi/test_specification.py
Close #146 
```python
app.config.OAS_CUSTOM_FILE = "/path/to/my/oas.json"
```
=> Allow for custom OAS files

sanic_ext/extras/validation/decorator.py, tests/extra/test_validation_multiple.py
=> Both body and query validation

sanic_ext/extras/validation/check.py, tests/extra/test_validation.py
=> Do not coerce a literal type

sanic_ext/extensions/openapi/types.py, tests/extensions/openapi/test_model_fields.py
=> Do not pass items twice to Array

sanic_ext/extras/validation/validators.py, tests/extra/test_validation_pydantic.py
Passing exception pydantic object as extra argument to write custom messages to the http client.
=> feat: passing exception to extra argument

sanic_ext/extensions/health/endpoint.py
=> Healthcheck Endpoint Fix

sanic_ext/extensions/http/methods.py, sanic_ext/extensions/openapi/types.py, tests/extensions/http/test_methods.py
=> Do not fail on cython objects

sanic_ext/bootstrap.py, sanic_ext/extensions/injection/constructor.py, sanic_ext/extensions/injection/registry.py, tests/extensions/injection/test_add_dependency.py
Explicit set of request argument on an injection
Closes #180
=> Force request property for injections

sanic_ext/extensions/openapi/types.py, tests/extensions/openapi/test_typing.py, tox.ini
=> Enable foo | None for nullable=True

sanic_ext/extensions/logging/logger.py
=> Fix #202: reduce CPU in logging

sanic_ext/extensions/templating/engine.py, sanic_ext/extensions/templating/render.py, tests/extensions/templating/templates/request_test.html, tests/extensions/templating/test_templating.py
As discussed on Discord, this adds the current `request` to the default template context in Jinja.
=> Adds current request to default template context

sanic_ext/extensions/openapi/blueprint.py, tests/extensions/openapi/test_paths.py
https://github.com/sanic-org/sanic-ext/issues/211
=> Removed uri ending slash trim from the doc paths

sanic_ext/extensions/openapi/definitions.py, tests/extensions/openapi/test_definitions.py
Closes https://github.com/sanic-org/sanic-ext/issues/214
=> Replaced default list server variables with object

sanic_ext/config.py, sanic_ext/extensions/http/cors.py, sanic_ext/extensions/http/methods.py, sanic_ext/extensions/injection/injector.py, sanic_ext/extensions/openapi/blueprint.py, tests/extensions/injection/test_injection_config.py
Needed to change some ordering
=> Fix late dependency registration
